timeframe: 1d
run_schedule: after_close
universe:
- BTCUSDT
- ETHUSDT
- AAPL
- MSFT
- SPY
risk_per_trade: 0.02
max_positions: 5
enforce_cash_settlement: true
warn_pdt_trades: true
default_order_type: limit
universe_equities:
- BTCUSDT
- ETHUSDT
- AAPL
- MSFT
- SPY
universe_crypto:
- BTCUSD
- ETHUSD
- SOLUSD
- DOGEUSD
- USDCUSD
adaptive_universe: false
risk:
  percent_cash_per_trade: 0.2
  max_risk_dollars: 10
  max_positions: 5
  enforce_cash_settlement: true
pipeline:
  daily_run_time_local: 19:15 America/Los_Angeles
  auto_push: false
